mysql:
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: "password"

quests:
  example:
    Stages: 2
    1:
      NPC-ID: 13
      delay: 100
      Messages:
        - "&7Tekst"
        - "&7Drugi tekst"
    2:
      NPC-ID: 14
      delay: 100
      Messages:
        - "&7Tekst2"
  example2:
    Stages: 1
    1:
      NPC-ID: 12
      delay: 100
      Messages:
        - "&7Tekst3"